zurichat/zc_main

lib/index.js

This commit adds lib folder and an index.js file that serves as export for all modules in the folder. The lib folder is where all backend services are written and exported for us.

adds lib folder and lib/index.js file close #569

---

routes/api.js

The authentication endpoints for login and register have been set up to communicate with the Zuri core auth API #558 and #557

created auth endpoints for login and register

---

zc_frontend/src/pages/signup/index.js
zc_frontend/src/styles/Signup.module.css

added sign-up button component close #287

---

zc_frontend/src/components/ProfileMenu.js
zc_frontend/src/styles/ProfileMenu.module.css

**Created the header profile menu component and added online presence to it.**
issue: [my online presence icon should be green](https://github.com/zurichat/zc_main/issues/289)

Added profile menu component with online presence issue #289

---

lib/index.js

Revert "adds lib folder and lib/index.js file close #569"

---

lib/email_verify.js
package-lock.json
zc_frontend/package-lock.json

I added two functions to the lib folder that handles email verification after a user has been validated to login. The first function sends the verification link to the user to click and it depends on a **mailFunc()**, imported from my team members file and the second function is one that would be called to verify the mail by comparing two token values for equality

email verification upon registration success close #150

---

middlewares/getDevice.js
package.json
routes/api/index.js
server.js
yarn.lock

Implemented a function to notify a user of a new device logged on. testing as a route. fix #153 
It gets the user device, user browser, user phone name, IP address, and location.
Testing linking on https://zuri.chat/api/test/deviceinfo
It would be added as a middleware when the login module is created.

Middleware to retrieve new logged in device information. fix #153

---

package.json
zc_frontend/src/components/externalPagesComponents/Input.js

I created a input components inside the component/external pages. Here is the link to the hosted version for preview : https://input-compomponent.netlify.app/

Created a input component for the external pages

---

lib/user_session.js
middlewares/getSession.js
package.json
routes/api/index.js
server.js
yarn.lock
zc_frontend/package.json

Revert "Revert "Feat/user sessions""

---

middlewares/getDevice.js

Revert "Logging information of new device sign in. update to fix #153"

---

zc_frontend/src/App.js
zc_frontend/src/pages/features/components/SpecialFeatures.js
zc_frontend/src/pages/features/styles/SpecialFeatures.css

special features you didn't know you needed

---

zc_frontend/src/pages/features/components/Section2.js

Built a responsive section 2 of the zuri chat featured page.
below is the link to the live https://sec-2.netlify.app/

Feat/Section 2 Chat Feature page

---

zc_frontend/src/components/SearchResults3.js
zc_frontend/src/styles/SearchResults3.module.css
zc_frontend/yarn.lock

Using the above figma view I created the search section. I have attached the views on mobile, tablet and desktop views
Tablet view
Desktop view
Mobile view

created search section 3

---

zc_frontend/src/components/usePasswordVisibilityReducer.js
zc_frontend/src/pages/signup/index.js
zc_frontend/src/styles/Signup.module.css

Wrote the logic for making the visibility icon appear when the user starts typing in the input field for password and also the logic for when the user wants to know if what he/she typed was correct by clicking the icon to toggle between showing or hiding the password actual characters. I also created/added custom reducer hook for reusability and managing state relating to password visibility.

Fixed issue #613 by Ofili chukwuemeka - Team Einstein

---

lib/logout.js
server.js

This feature redirect the user to the login route.
Note: The login route is not yet created for the backend so it won't go to the login route now, it would just go the home page (zuri.chat)
close issue #564 (Team Einstein)
The testing link https://zuri.chat/logout

adds logoutfeature to the logoutpage

---

package.json
server.js

This adds cors configurations to server

adds cors to server

---

zc_frontend/src/assets/lock.svg
zc_frontend/src/assets/toggle.svg
zc_frontend/src/pages/cookies-settings/index.js
zc_frontend/src/pages/cookies/index.js
zc_frontend/src/pages/features/components/Section1.js
zc_frontend/src/pages/features/styles/Section1.module.css
zc_frontend/src/pages/security/components/SecurityFeature.js
zc_frontend/src/pages/security/index.js
zc_frontend/src/pages/security/styles/security_features.module.css
zc_frontend/src/styles/Cookies.modules.css
zc_frontend/src/styles/CookiesSettings.module.css

This is a mobile responsive page for mobile users ONLY. It is a cookie setting section of the main app that gives users access to control various types of cookies. It consists of a learn more link and others.
**Zurichat hosted link:**
**Netlify live link:** [cookies-settings](https://cookies-setting-mobile-view.netlify.app/)
**Link to figma-design:** [Figma Design](https://www.figma.com/file/ZxO7DXY7q1P4wFpj3eKwwL/Aristotle-Workspace-(Copy)?node-id=933%3A3094)
fixes #748

Feat/cookies settings mobile #748

---

zc_frontend/src/components/externalPagesComponents/cookiesSetting/index.html
zc_frontend/src/components/externalPagesComponents/cookiesSetting/script.js

this is a cookie setting for cookies to appear and disappear on the website.

adds cookiessettings  close #24

---

zc_frontend/src/components/externalPagesComponents/Resources/SectionFour/SectionFour.js
zc_frontend/src/pages/resources/card_component/Card.css
zc_frontend/src/pages/resources/components/section1.js
zc_frontend/src/pages/resources/index.js
zc_frontend/src/pages/resources/styles/Section1.module.css
zc_frontend/src/pages/resources/styles/section4.css

Fix Resource Page Bug

---

zc_frontend/src/components/externalPagesComponents/Resources/SectionFour/SectionFour.js
zc_frontend/src/pages/resources/card_component/Card.css
zc_frontend/src/pages/resources/components/section1.js
zc_frontend/src/pages/resources/index.js
zc_frontend/src/pages/resources/styles/Section1.module.css
zc_frontend/src/pages/resources/styles/section4.css

Revert "Fix Resource Page Bug"

---

yarn.lock
zc_frontend/package.json
zc_frontend/src/pages/login/index.js
zc_frontend/yarn.lock

Implement  Login page to retrieve token from zc_core
Save token globally and redirect to the dashboard

Section one page(Retrieve token, Save Token and Redirect)

---

zc_frontend/src/components/TopbarModal.js
zc_frontend/src/styles/StatusBadge.module.css
zc_frontend/src/styles/Topbar.module.css

I implemented fixing the drop menu on the user icon at the top bar on https://zuri.chat/home as instructed by Mark in one the tickets I picked and was assigned to.
This has been verified and confirmed by the design team in team Einstein.
link to design: https://www.figma.com/file/l3II6yr9uzCffjnaNEnszn/Sub-Team-2-(Einstein)?node-id=0%3A1
View:

Fixed the drop menu on the user icon, so it is positioned properly

---

zc_frontend/src/components/AuthFormWrapper.js
zc_frontend/src/pages/login/index.js
zc_frontend/src/pages/signup/index.js

Added authentication to login and signup page

Authentication

---

zc_frontend/src/components/StatusBadgeModal.js
zc_frontend/src/components/TopbarModal.js
zc_frontend/src/styles/StatusBadgeModal.module.css
zc_frontend/src/styles/Topbar.module.css

I implemented changes in the status badge and the placeholder carrying the status badge in the user icon drop menu in accordance with the Figma style design.
The changes are as follows:
1. Ensure that the status badge in the drop menu of the user icon is not clickable
2. Ensure that the placeholder holding the status badge in the user icon drop menu has no borderline color when clicked
3. Ensure that the placeholder is not clickable
4. Ensure that the status badge in the user icon drop menu is not surrounded by any colored borderline.

Implemented changes on the status badge and status badge placeholder

---

sidebar/src/utils/links.js
src/index.ejs
src/zuri-root-config.js

- added proper cdn for popper and bootstrap
- corrected notifications plugin to noticeboard

Corrected Noticeboard plugin

---

control/src/pages/ReportFeature/components/AdminSetup.js
control/src/pages/ReportFeature/components/ComplaintProfiles.js
control/src/pages/ReportFeature/components/Confirm.js
control/src/pages/ReportFeature/components/Form.js
control/src/pages/ReportFeature/components/Success.js
control/src/pages/ReportFeature/components/reports.module.css
topbar/src/TopNavBar.js

The report button is beside profile picture.
https://zuri.chat/home

Reports feature on zuri's homepage

---

control/src/pages/workspace/components/WorkspaceCard.js
control/src/pages/workspace/style/workspace.module.css

Increased the specificity of some css elements to override generic styling and also made the displayed email dynamic in the workspace card component.

Made adjustment to  the styling and card component for workspace screen

---

topbar/src/TopNavBar.js
topbar/src/components/TopbarModal.js
topbar/src/context/ProfileModal.js
topbar/src/context/Topbar.js
topbar/src/styles/StatusBadgeModal.module.css
topbar/src/styles/Topbar.module.css
topbar/src/utils/Api.js

I implemented my workflow below in accordance with the Figma design from the design team.
ZURI MAIN
USER STORY: As a User, when I click on the user Icon I want to be able to see the drop menu which shows the user information e.g. my status, whether I am active or away, etc. :
WORK FLOW:
1. click User icon
2. modal for drop menu should appear
3. changing away and active status according to the figma design
Team:
FE (@Ejike ) :
1. Ensure that the status badge in the drop menu of the user icon is not clickable
2. Implement change away and active status to reflect on the user icon drop menu modal
3. Ensure that the placeholder holding the status badge in the user icon drop menu has no borderline color when clicked.
4. Ensure that the placeholder is not clickable
1 BE (@Enike): Ensure the …

ZURI MAIN WORK FLOW

---

control/src/pages/download/DownloadsAndroid.js
control/src/pages/download/DownloadsDesktop.js
control/src/pages/download/DownloadsIOS.js
control/src/pages/download/styles/DownloadsAndroid.module.css
control/src/pages/download/styles/DownloadsIOS.module.css
control/src/pages/download/styles/download.module.css

modified mobile view of download page

Mobile view Download Page

---

package.json
topbar/src/components/EditProfile.js
topbar/src/styles/StyledEditProfile.js
topbar/src/utils/Api.js
yarn.lock

new Update Profile Picture

---

topbar/src/TopNavBar.js
topbar/src/components/EditProfile.js
topbar/src/components/LanguageAndRegion.js
topbar/src/components/MarkAsRead.js
topbar/src/components/NotificationPreference.js
topbar/src/styles/LanguageAndRegion.module.css
topbar/src/styles/MarkAsRead.module.css
topbar/src/styles/StyledEditProfile.js
topbar/src/utils/Api.js

New upload picture

---

control/src/zuri-control.js
topbar/package.json
topbar/src/components/SetStatusModal.js
topbar/yarn.lock

Minor fixes to make it work.

---

control/src/pages/events/styles/events.module.css

Worked on the texts , padding  and font color styles of the events page while comparing it with the figma designs of the Eventsflow and the corrections pointed out. 
Attached here are screenshots of the page .

Format feat/eventflow

---

control/src/pages/careers/components/Section3.js
control/src/pages/careers/components/sectionOne.js
control/src/pages/careers/styles/CareersSection2.module.css
control/src/pages/careers/styles/section3.module.css
control/src/pages/careers/styles/sectionOne.module.css

I adjusted the page based on the recent changes that was made Yesterday.

Editing the Button and Aligning the Texts

---

control/src/component-styles/FooterStyle.module.css
control/src/component-styles/HeaderStyle.module.css
control/src/components/Header.js

Header and Footer modifications effected inline with the design and Mark's corrections.
Desktop view
iPad view
Mobile View

Header and Footer Modifications

---

control/src/pages/passwordReset/index.js
control/src/pages/passwordReset/newPassword.jsx
control/src/pages/passwordReset/verifyCode.jsx
yarn.lock

Revert "password reset update"

---

topbar/src/components/AdvancedSettings.js
topbar/src/components/AudioVideo.js
topbar/src/styles/AdvancedSettings.module.css
topbar/src/styles/AudioVideo.module.css

style adjustments for advanced settings & audio and video page under preferences screen

advanced settings and audio and video pages restyling- Preference pages- Team Einstein

---

topbar/src/components/AudioVideo.js
topbar/src/styles/AudioVideo.module.css

implementation of new design on advanced settings and audio and video page

buttons and page adjustment- Preferences screen- Team Einstein

---

sidebar/src/components/Drop.js

Added route to channels and dms from dropdown

---

control/src/pages/workspace/components/WorkspaceContext.js
control/src/pages/workspace/components/workspaceReducer.js
package.json
yarn.lock

Dev ct workspace fix

---

control/src/pages/inviteScreen/index.js

Revert "Update index.js"

---

control/src/component-styles/FooterStyle.module.css
control/src/components/Footer.js
control/src/components/Header.js

Footer redesign implemented.
Desktop view
iPad View
Mobile view

Footer modification

---

pluginHeader/src/styles/header.module.css
src/index.ejs

Revert "Added plugin header to import map"

---

control/src/component-styles/SignoutStyle.js

Signout page fix

---

control/src/pages/cookies/index.js
control/src/pages/cookiesSettings/ToggleButton.js
control/src/pages/cookiesSettings/index.js
control/src/pages/cookiesSettings/styles/CookiesSettings.module.css

Modification to the Cookie Setting page in accordance to design
<h4>How it looks</h4>
Desktop Views
iPad View
iPhone X view
Mobile View

Cookie Settings Page

---

src/index.ejs

Added google search engine tags 
fix twitter , Facebook and Linkedin tags.
Register zuri.chat for scraping

add search-engine tags, fix twitter , facebook and linkedin tags

---

sidebar/src/components/Drop.js
sidebar/src/sidebar.component.js

Revert "sidebar rtc update"

---

control/src/pages/createworkspace/components/CompanyName.js
control/src/pages/createworkspace/components/WorkspaceHome.js
control/src/pages/signout/index.js
package.json
sidebar/src/components/ModalComponent.js
topbar/src/components/TopbarModal.js
yarn.lock

Revert "Create work space fix and sign out"

---

control/src/pages/createworkspace/components/CompanyName.js
control/src/pages/createworkspace/components/WorkspaceHome.js
control/src/pages/signout/index.js
sidebar/src/components/ModalComponent.js
topbar/src/components/TopbarModal.js

Fixed All Bugs Related Creation Of Workspace/organization 
Wrote and Implement a function to log user out of an organization
Redesigned SignOut Page/UI

Fixed all Bug Related To Creation of Workspacs and Fix Signout Page

---

control/src/App.js

Revert "browser-notifications"

---

commentSidebar/src/components/ChatItem..js
commentSidebar/src/components/Chats.js
commentSidebar/src/components/CommentBox.js
commentSidebar/src/components/CommentSection.js
commentSidebar/src/root.component.js
commentSidebar/src/zuri-comment-sidebar.js
control/src/App.js
src/zuri-root-config.js

proof of concept for comment sidebar

first proof of concept for comment sidebar

---

commentSidebar/src/components/Chats.js
commentSidebar/src/root.component.js

Task; Create a set of functions for the sidebar comments to be assembled by plugins whenever needed.
Worked on this with @YG on our slack workspace. Mounted it as an SPA instead of a basic react UI.
Tested it locally with sales plugin but it can't be live now due to Mark's orders.

Contributions to the sidebar comments

---

packages/control/src/App.js
packages/control/src/component-styles/FooterStyle.module.css
packages/control/src/component-styles/HeaderStyle.module.css
packages/control/src/components/GeneralErrorBoundary.js
packages/control/src/components/GeneralLoading.js
packages/control/src/pages/LandingPage/styles/LandingPage.module.css

TODO 
- Improve granularity of error boundaries 
- Improve chunking of related pages
- Customized fallback components?

[Feat] Lazy Loading

---

packages/control/src/components/Protected/TopBar/src/components/TopbarModal.js
packages/control/src/components/Protected/TopBar/src/styles/Topbar.module.css

Styled Drop Menu

---

packages/control/src/components/Protected/Sidebar/src/App.js
packages/control/src/components/Protected/Sidebar/src/utils/plugindata.js

- accepts multiple sidebar payload

refactor sidebar to provide for multiple plugin sidebar data

---

packages/control/src/components/Protected/Sidebar/src/utils/plugindata.js
packages/control/src/pages/Protected/CreateWorkspace/LaunchWorkspace.js

- check if sidebar response is an array[] before checking if it's a javascript object{}

update sidebar to first check if plugin sidebar response is an array

---

.whitesource
packages/control/src/components/Protected/Sidebar/src/App.js
packages/control/src/components/Protected/Sidebar/src/utils/plugindata.js
packages/control/src/pages/Protected/CreateWorkspace/LaunchWorkspace.js

Merge Dev to Staging

---

packages/control/src/components/Protected/Sidebar/src/components/Room.js
packages/control/src/components/Protected/Sidebar/src/components/RoomItem.js
packages/control/src/components/Protected/Sidebar/src/sidebar.component.js
packages/control/src/components/Protected/Sidebar/src/utils/plugindata.js
packages/control/src/components/UserOrganisationsListing/UserOrganisationsListing.js
packages/root-config/src/applications.js

- implement correct route link on the sidebar to plugins

improve sidebar logic

---

packages/control/src/components/Protected/Sidebar/src/components/Room.js
packages/control/src/components/Protected/Sidebar/src/components/RoomItem.js
packages/control/src/components/Protected/Sidebar/src/sidebar.component.js
packages/control/src/components/Protected/Sidebar/src/utils/plugindata.js
packages/control/src/components/UserOrganisationsListing/UserOrganisationsListing.js
packages/control/src/pages/Protected/CreateWorkspace/LaunchWorkspace.js
packages/root-config/src/applications.js

Merge Dev into Staging

---

packages/control/src/pages/SignOut/SignOut.js
packages/control/src/pages/Static/ContactUs/components/contactFormContainer/contactFormContainer.js
packages/control/src/pages/Static/ContactUs/components/contactFormContainer/faq/en.js
packages/control/src/pages/Static/ContactUs/components/contactFormContainer/faq/es.js
packages/control/src/pages/Static/ContactUs/components/contactFormContainer/faq/fr.js
packages/control/src/pages/Static/ContactUs/components/contactFormContainer/faq/index.js
packages/control/src/translations/translation-dictionary/index.js
packages/control/src/translations/translation-dictionary/pages/SignOut.js

- Espanyol Translation added for FAQs
- Signout page translation fixed

Espanyol Translation for FAQs   and Signout page translation fix

---

packages/utilities/src/zuri-utilities.js
packages/zuriUi/src/components/message-board/MessageBoard.jsx

- fix build error
- update `GetWorkspaceUser` return object

fix build error

---

packages/control/src/App.js
packages/control/src/auth/use-auth.js
packages/control/src/components/EmailVerificationModal/EmailVerificationModal.js
packages/control/src/components/Form/AuthFormWrapper.js
packages/control/src/pages/Login/Login.js
packages/control/src/pages/Protected/ChooseWorkspace/ChooseWorkspace.js
packages/control/src/pages/SignOut/SignOut.js
packages/control/src/pages/SignUp/SignUp.js
packages/control/src/root.component.js
packages/control/src/utils/withSuspense.js
packages/utilities/src/zuri-utilities.js
packages/zuriUi/src/components/message-card/components/message-box/MessageBox.jsx

- protect private routes
- prevent unnecessary API call at "/choose-workspace"
- fix signup bug
- clear storage and cache on signout

improve authentication workflow

---

packages/control/src/auth/use-auth.js

- reset user state to null on signout

fix bug with signout

---

packages/control/src/pages/Protected/Workspace/Workspace.style.js
packages/zuriUi/src/components/message-board/MessageBoard.styled.js

Responsive redesign

---

packages/control/src/components/Protected/Sidebar/src/components/RoomItem.js
packages/control/src/components/Protected/Sidebar/src/components/SingleRoom.js
packages/control/src/components/Protected/Sidebar/src/styles/Drop.module.css

- Make the selection mark of the selected item to be darker

style sidebar active items

---

packages/control/src/components/Protected/Sidebar/src/components/Header.js
packages/control/src/components/Protected/Sidebar/src/styles/Sidebar.module.css

- Position the name of workspace well

style sidebar header

---

packages/control/src/pages/Protected/Workspace/Workspace.js
packages/root-config/src/index.ejs
packages/utilities/src/zuri-utilities.js

- Set the title of the page properly, depending on the room selected

add document title to pages

---

packages/zuriUi/src/components/message-editor/message-input/MessageInput.jsx
packages/zuriUi/src/components/message-editor/message-input/components/Toolbar.jsx

Worked on the Message Board, Message Input

Zc-improvement

---

package.json
packages/control/src/auth/use-auth.js
packages/control/src/components/GoogleAuth/index.js
packages/zuriUi/package.json
packages/zuriUi/src/components/message-board/MessageBoard.jsx
yarn.lock

- When I switch to another channel and switch back
- Auth 1 : GoogleAuth

ZUR-49 When I switch to another channel and switch back

---

packages/control/src-old/components/GoogleAuth.js
packages/control/src-old/pages/admin/InviteModal.js
packages/control/src-old/pages/admin/components/ContactTab.js
packages/control/src/auth/use-auth.js
packages/control/src/components/GoogleAuth/index.js
packages/control/src/components/Protected/Sidebar/src/components/PluginRoomAddUser.js
packages/control/src/components/Protected/Sidebar/src/components/RoomItem.js
packages/control/src/components/Protected/Sidebar/src/components/invite-workflow/newInviteModal/new-invite.utils.js
packages/control/src/components/Protected/Sidebar/src/utils/Api.js
packages/control/src/components/Protected/TopBar/src/components/MessagesMedia.js
packages/control/src/components/Protected/TopBar/src/components/TopbarModal.js
packages/control/src/components/Protected/TopBar/src/utils/Api.js
packages/control/src/components/SubscribeToNewsletter/SubscribeToNewsletter.js
packages/control/src/pages/Protected/ChooseWorkspace/ChooseWorkspace.js
packages/control/src/pages/Protected/CreateWorkspace/LaunchWorkspace.js
packages/control/src/pages/Protected/CreateWorkspace/Step0.js
packages/control/src/pages/Static/ContactUs/components/contactFormContainer/contactFormContainer.js
packages/control/src/pages/Static/Plugins/components/EmailSubForm1.js
packages/control/src/pages/Static/Plugins/components/Subscribe1.js
packages/marketplace/src/marketplace/components/MarketPlaceContainer.js
packages/marketplace/src/marketplace/marketplace.js
packages/utilities/src/zuri-utilities.js
packages/zuriUi/src/components/PluginModal/PluginModal.jsx
packages/zuriUi/webpack.config.js

- create a BASE_URL utility variable 
- refactor all API calls

switch all API calls to zuri core staging

---

packages/zuriUi/src/components/message-board/MessageBoard.jsx

- add loading UI to message board

show loading UI

---

packages/control/src-old/components/TopbarModal.js
packages/control/src/components/Protected/TopBar/src/TopNavBar.js
packages/control/src/components/Protected/TopBar/src/styles/TopBarSearchModal.module.css
packages/control/src/components/Protected/TopBar/src/styles/TopNavBar.module.css
packages/control/src/components/Protected/TopBar/src/styles/Topbar.module.css
packages/control/src/pages/Protected/Workspace/Workspace.js
packages/control/src/pages/Protected/Workspace/Workspace.style.js

Changed layout of workspace

---

packages/control/src/components/Protected/Sidebar/src/components/invite-workflow/newInviteModal/EmailInviteModal.js
packages/control/src/components/Protected/Sidebar/src/components/invite-workflow/newInviteModal/Step1.js
yarn.lock

- Fixed send button bug on invite modal

Fixed send button bug on invite modal

---

packages/control/src/pages/InvitePage/index.js
packages/control/src/pages/ResetPassword/ChangePassword.js
packages/control/src/pages/ResetPassword/PasswordSuccesful.js
packages/control/src/pages/ResetPassword/VerifyCode.js
packages/control/src/pages/ResetPassword/index.js

- redirect users to the login page after a successful password reset
- use `BASE_URL` from zuri utilities

fix password recovery bug

---

.eslintrc.json
package.json
packages/control/jest.config.js
packages/control/jest.setup.js
packages/control/package.json
packages/control/src/__mocks__/fileMock.js
packages/control/src/__mocks__/zuriUtilities.js
packages/control/src/pages/Home/__tests__/Home.test.jsx
packages/root-config/babel.config.json
packages/root-config/cypress.json
packages/root-config/cypress/fixtures/example.json
packages/root-config/cypress/integration/home_page.spec.js
packages/root-config/cypress/integration/locators.spec.js
packages/root-config/cypress/plugins/index.js
packages/root-config/cypress/support/commands.js
packages/root-config/cypress/support/index.js
packages/root-config/package.json
yarn.lock

- setup unit and integration testing with jest and react-testing-library
- setup e2e testing with cypress
- add linting support for cypress

setup application testing structure

---

packages/main/src/components/form/AuthFormWrapper.module.css
packages/main/src/pages/login/Login.jsx
packages/main/src/pages/static/about/About.module.css
packages/main/src/pages/static/about/index.jsx
packages/main/src/translations/translation-dictionary/index.js
packages/main/src/translations/translation-dictionary/pages/About.js

Fixed the About page issues with the styling - ZCG13

Feat/aboutpage - ZCG-13

---

packages/main/src/components/form/AuthFormWrapper.module.css
packages/main/src/pages/login/Login.jsx

#ZCG20 - Added some small fixes to the login page as specified

Feat/loginpage - #ZCG20 - Added some small fixes to the login page

---

packages/main/src-old/components/Footer.js
packages/main/src/App.js

for Team Chisel (Carpenter) with URL - https://staging.zuri.chat/terms

Fixed terms of service page with ticket ID ZCG_18

---

packages/main/src/components/footer/Footer.jsx

Team: carpenter-team-ruler
issue id:  ZCG_11
removed legal and security links as we deemed them unnecessary for the average user. 
rearranged links among the available headers.
included divs and line breaks to style social media links
link to drive containing images as proof of usability [link](https://drive.google.com/drive/folders/1IVvT-LQ6FJWsOCf11OADiokbLJvlzvP0?usp=sharing)

Fix/Reduce footer links to only the essential-ZCG_11

---

packages/main/src/components/protected/topbar/components/TopNavbar.jsx
packages/main/src/components/top-navigation-bar/LanguageIcon.jsx

[ZCG_29] Added the language changing icon for logged in users #1826

---

packages/main/src/pages/static/privacy-policy/components/Content.js
packages/main/src/pages/static/privacy-policy/components/modal/Modal.module.css
packages/main/src/pages/static/privacy-policy/policyData.js
packages/main/src/pages/static/privacy-policy/styles/content.module.css

This fixes tiny issues with the modal used in the privacy policy page

fix privacy modal content

---

packages/main/src/components/top-navigation-bar/TopNavigationBar.module.css

The issue was to fix the clustered spacing of the middle section of the navbar on the home page. 
1.Before the fix:  ![Before-Fix](https://user-images.githubusercontent.com/61463830/201207164-b7c529e2-ef5a-4815-8ad1-e78a2c30f3ae.png)
2. After the fix:

ZUR-124 My PR adds a feature

---

packages/main/src/components/faq/index.jsx
packages/main/src/translations/translation-dictionary/index.js
packages/main/src/translations/translation-dictionary/pages/Pricing.js

I fixed the translation issue on the FAQ section of the pricing page

ZUR-197 fix the translation issue on the FAQ section of the Pricing Page

---

packages/main/src/pages/protected/create-workspace/Step3.jsx

A custom alert component has been created which replaces the default systems alert for "Get a shareable link" and is set to timeout after 2.3 seconds

feat: changed the alert method when the 'get a shareable link' is clicked.

---

packages/main/src/translations/translation-dictionary/index.js
packages/main/src/translations/translation-dictionary/pages/DownloadDesktop.js
packages/main/src/translations/translation-dictionary/pages/DownloadIos.js
packages/main/src/translations/translation-dictionary/pages/DownloadMac.js
packages/main/src/translations/translation-dictionary/pages/DownloadMobile.js
packages/main/src/translations/translation-dictionary/pages/DownloadWindows.js

This issue is fixed by creating translation files for the different download pages ie DownloadDesktop, DownloadMobile, DownloadIos, DownloadMac and DownloadWindows. The translation files include translations for the different available languages.

ZUR-192 My pull request fixes translations issue on the download page

---

packages/main/src/components/protected/topbar/styles/Topbar.module.css

ZCG_23 Fix: The drop menu is now well positioned

---

packages/main/src/pages/protected/create-workspace/Step0.jsx

I removed the icon showing three persons from this page.
linear app link - https://linear.app/zurichat2/issue/ZUR-138/remove-unnecessary-icons-in-the-create-workspace-page

ZUR-138 remove unnecessary icons from create workspace page

---

packages/main/src/components/protected/sidebar/styles/Drop.module.css

The channel groups title (the header for the dropdown in the sidebar chat list) was made darker(not black)

ZUR-108 : Feat/updatechannelgroupheader

---

packages/ui/src/message-room-details-dialog/MessageRoomDetailsDialog.jsx
packages/ui/src/message-room-view-header/MessageRoomViewHeader.jsx

Implemented the modal for the channel's description to work on desktop and mobile.

ZUR-164 Add the modal for the channels description

---

packages/main/src/pages/static/downloads/components/DownloadsDesktop.jsx
packages/main/src/pages/static/downloads/components/DownloadsMobile.jsx
packages/main/src/translations/translation-dictionary/index.js
packages/main/src/translations/translation-dictionary/pages/Download.js

ZUR-193 : Fix the translation language on the button (download page)

---

packages/main/src/components/protected/sidebar/styles/ModalComponentStyles.module.css

Workspace dropdown items change to a white text when you hover.

ZUR-112 My PR changes the workspace dropdown items color when hovered.

---

packages/main/src/components/footer/Footer.jsx
packages/main/src/translations/translation-dictionary/components/NavBar.js

The homepage now only has the relevant links

ZUR-129 My PR removes the unnecessary footer links in the Home Page

---

packages/main/src/components/protected/topbar/styles/Topbar.module.css

Reduce the gap in the profile dropdown -close ZUR-101-

ZUR-101 My PR Reduce the gap in the profile dropdown

---

packages/main/src/components/protected/topbar/components/NewStatusModal.jsx
packages/main/src/components/protected/topbar/styles/SetStatusModal.module.css

**Link to issue: https://linear.app/zurichat2/issue/ZUR-104/patch-distortions-in-the-scrollable-container-and-the-modal-title-in**
**Before:**
- Set status title wasn't aligned properly.
**After:**
- Set status title aligned properly.
**Tab responsive:**
**Mobile responsive:**

ZUR-104 My PR patches distortions in the set status modal.

---

packages/main/src-old/pages/termsOfService/components/content.js

I cleaned up the legal (terms) page, which was previously filled with dummy text(lorem ipsum), and added the GeneralLoading component with the text: 404 - (Refactoring in Progress)
slack username: Liquidঐ
linear: liquid

ZUR-151 My PR cleans up the legal page and added the loader component

---

docs/CONTRIBUTING.md
packages/main/src/pages/static/contact-us/components/ContactFormContainer.jsx

Link: https://github.com/nnaemekaxi/zc_main/tree/contact-us-page
Linear ID: ZUR-121 The contact page in the login form is not working 
Bugs Fixed: async and await added (lines 34 & 35) of ContactFormContainer

ZUR-121 fixed the contact us page in the login form

---

packages/main/src/pages/home/Home.jsx
packages/main/src/pages/home/Home.module.css

**Redesign the home page**
[screen-capture.webm](https://user-images.githubusercontent.com/78821732/201381023-b07d8ffb-c779-4664-a35c-87791ca7debe.webm)

ZUR-128: Redesign HomePage

---

.vscode/settings.json
packages/ui/src/message-room-details-dialog/MessageRoomDetailsDialog.jsx
packages/ui/src/message-room-details-dialog/components/AddMemberModal.jsx
packages/ui/src/message-room-view-header/MessageRoomViewHeader.jsx
packages/ui/src/utils/samples/sample-member-list.js

**Before**
https://user-images.githubusercontent.com/47562075/201494878-83f88f69-db63-49ae-8c66-3f3eca54f951.mp4
**After**
https://user-images.githubusercontent.com/47562075/201494847-68534d70-82bd-44d0-88e6-a53f52df9509.mp4
Closes #2610

Add the ability to add people via the channels modal - ZUR-168

---

packages/main/src/components/protected/sidebar/styles/ModalComponentStyles.module.css

Fixing Workspace dropdown items (Adding spaces)

---

packages/main/src/components/top-navigation-bar/TopNavigationBar.jsx
packages/main/src/components/top-navigation-bar/TopNavigationBar.module.css
packages/main/src/pages/static/contact-us/components/ContactFormContainer.jsx

Removed the contact link from the navigation tab and worked on the margin problem as requested.

Contact link added to the bottom of the page #134

---

packages/main/src/App.js
packages/main/src/components/footer/Footer.jsx
packages/main/src/components/protected/sidebar/components/ModalComponent.jsx
packages/main/src/components/protected/topbar/components/TopbarModal.jsx
packages/main/src/components/top-navigation-bar/TopNavigationBar.jsx

**My PR Fixes ZUR-132**
Remove the downloads page and links to it
Changed files to remove pages being linked to the download page
Before:
After:

ZUR 132: Remove the downloads page and links to it

---

packages/ui/src/message-room-view-header/MessageRoomViewHeader.jsx

I was told to make the username in the chat header pane from displaying twice.
I deleted the extra username logic
- [ x] My code follows the code style of this project.
- [x ] This PR does not contain plagiarized content.
- [x ] The title and description of the PR is clear and explains the approach.
- [x ] I am making a pull request against the **dev branch** (left side).
- [x ] My commit messages styles matches our …

FEAT fix - fixed the username displaying twice in the chat pane header

---

packages/ui/src/message-room-details-dialog/MessageRoomDetailsDialog.jsx

This is a picture of how it looked like before👇
And this is the fix👇
@JulianaSau

Fix: Addressed the z-index issue with the channels description modal.

---

packages/main/src/translations/translation-dictionary/pages/Pricing.js

( This is a linear ticket )
**My PR Fixes ID-linear_ticket_number_196**
**Before**
**After**
[New Recording - 11_16_2022, 2_22_25 AM.webm](https://user-images.githubusercontent.com/63173100/202060461-f74f4ca1-8d62-4439-8e54-d4347acfb706.webm)
**NEW UPDATE ON BOTTOM BUTTON TRANSLATION**

ZUR-196 My PR adds a feature

---

packages/main/src/auth/use-auth.js
packages/main/src/pages/login/Login.jsx
packages/main/src/pages/protected/workspace/Workspace.jsx
packages/ui/src/message-pane-input/MessagePaneInput.jsx

**My PR Fixes ID-178**
Persist the last view i was in. whether a chat or a plugin.
Persist chat state for each room to sessionStorage.
https://user-images.githubusercontent.com/58990930/202037829-e7f5c944-bcb9-4127-ae92-16d74859e6a3.mp4

ZUR-178 Persist last view

---

.github/pull_request_template.md
packages/main/src/components/protected/sidebar/components/Drop.jsx

Fix errors in code
Update PR template instructions

Fix: fix syntax errors in `Drop.jsx`

---

packages/main/src/components/protected/sidebar/components/Sidebar.jsx
packages/main/src/components/protected/topbar/components/SidebarPreference.jsx
packages/main/src/pages/protected/workspace/Workspace.jsx

Revert "Ticket ID ZCG_5: Remove the All DMs functionality"

---

packages/main/src/components/protected/sidebar/components/Header.jsx
packages/main/src/components/protected/topbar/components/TopNavbar.jsx
packages/main/src/pages/protected/workspace/Workspace.jsx
packages/main/src/pages/protected/workspace/Workspace.module.css

- https://linear.app/team-boots-workspace/issue/TEA-117/code-the-design
- https://linear.app/team-boots-workspace/issue/TEA-124/data-fetching
My PR Fixes TEA-117 and TEA-124
- I was asked to code the sidebar according to the designs a designer made and also fetch data
I worked on the workspace files and added the stylings. I also had to use axios to pull in workspaces for the user

Feat: TEA 117 and TEA124 Code the sidebar from slack for multiple workspaces and fetch data

---

packages/main/src/components/footer/Footer.jsx

https://linear.app/team-mallet/issue/FE-41/translate-zuri-chat-footer-component
**My PR Fixes FE-41 /translate-zuri-chat-footer-component**
translate-zuri-chat-footer-component
I already translated the page but needed to fix the align right for Arabic and Hebrew languages
eos

Feat: FE-41/Translate Zuri-Chat Footer Component

---

packages/main/src/translations/translation-dictionary/pages/SignOut.js

Signout page translation/ FE-58
**My PR Fixes ID-linear_ticket_number_here**  FE-58
Translate signout page
i added more laguages to the Json signout file, 
no dependencies installed
-  [x] My code follows the code style of this project.
before changes
after changes

FE-58 Fix translation on sign out page

---

packages/main/src/components/protected/sidebar/components/EditWorkspaceModal.jsx
packages/ui/src/message-board/MessageBoard.jsx

Revert "GG-27 Fix scroll issues/ chat pagination"

---

packages/main/src/components/top-navigation-bar/TopNavigationBar.jsx
packages/main/src/components/top-navigation-bar/TopNavigationBar.module.css
packages/main/src/pages/static/privacy-policy/components/Content.js
packages/main/src/pages/static/privacy-policy/styles/content.module.css
packages/ui/src/message-pane-input/MessagePaneInput.jsx

Fixed global css issue affecting navbar
Fixed error in MessagePaneInput.jsx

Fix errors arising from MessagePaneInput.jsx

---

packages/main/src/components/admin-sidebar/utils/Common.jsx
packages/main/src/components/protected/topbar/components/TopNavbar.jsx
packages/main/src/pages/protected/admin-settings/AdminSettings.jsx
packages/main/src/pages/protected/settings-home/utils/Common.jsx
packages/root-config/src/assets/plugin.importmap.json

Fix bugs in admin settings and zc_messaging import 

---

packages/main/src/components/protected/sidebar/styles/Sidebar.module.css
packages/main/src/components/protected/topbar/components/NotificationPreference.jsx
packages/main/src/components/protected/topbar/components/Profile.jsx
packages/main/src/components/protected/topbar/components/ProfileMore.jsx
packages/main/src/components/protected/topbar/components/TopbarModal.jsx
packages/main/src/components/protected/topbar/hooks/useClickOutside.jsx
packages/main/src/components/protected/topbar/styles/Profile.module.css
packages/main/src/components/protected/topbar/styles/Topbar.module.css

Fixed profile ui issues
1. Align profile with top navigation
[New Recording - 27_11_2022, 16_40_37.webm](https://user-images.githubusercontent.com/47562075/204154753-5374a9aa-05eb-486e-a15b-45c36c6f2af1.webm)

fix: fixed profile ui issues

---

packages/ui/src/message-room-details-dialog/MessageRoomDetailsDialog.jsx
packages/ui/src/message-room-details-dialog/components/AddMemberModal.jsx

**My PR Fixes ID-FRO-83**
Add people to channel functionality
- Made changes in the **MessageRoomDetailsDialog.jsx** and **AddMemberModal.jsx**
- Created a searchList state array
- created a set to handle memberlist.
- Check to see if members in the set exist in the user list.
- All members not in the user list are then added to the searchlist.
- In the add member modal, the option attribute of search tag is the assigned the searchlist value.
- This function implies that all members of a channel will not exist in the search bar for users to be added. 
🚨Please review the [style guide for contributing](https://github.com/zurichat/zc_main/blob/dev/docs/STYLING.md) and [guidelines for …

feat(FRO-83): add people to channel functionality

---

.npmrc
package.json

**My PR Fixes ID-FRO-83**
Told to remove the .npmrc file and remove the lock on the node version in the package.json.
- Deleted the .npmrc file to disable engine restriction
- modified engine in package.json to disallow lock on node version.

fix(FRO-83): removed engine restriction and node lock

---

packages/main/src/auth/use-auth.js
packages/main/src/components/admin-header/utils/Api.jsx
packages/main/src/components/admin-sidebar/utils/Api.jsx
packages/main/src/components/default-channel/DefaultChannel.jsx
packages/main/src/components/display-email/DisplayEmail.jsx
packages/main/src/components/display-name/DisplayName.jsx
packages/main/src/components/display-pronoun/DisplayPronoun.jsx
packages/main/src/components/manage-members/utils/Api.jsx
packages/main/src/components/notify-user/NotifyUsers.jsx
packages/main/src/components/protected/sidebar/components/EditWorkspaceModal.jsx
packages/main/src/components/protected/sidebar/components/ModalComponent.jsx
packages/main/src/components/workspace-language/WorkspaceLanguage.jsx
packages/main/src/pages/protected/about-workspace/utils/Api.jsx
packages/main/src/pages/protected/manage-workspace/utils/Api.jsx
packages/main/src/pages/protected/settings-home/utils/Api.jsx
packages/main/src/pages/protected/workspace/Workspace.jsx
packages/main/src/pages/static/sign-out/index.jsx
packages/marketplace/package.json

- replaced instances of the hard coded API url
- updated webpack build script

replaced instances of the hard coded zuri chat api link

---

packages/main/src/components/protected/sidebar/components/ModalComponent.jsx
packages/main/src/components/protected/topbar/components/EditProfile.jsx
packages/main/src/components/protected/topbar/components/NotificationPreference.jsx
packages/main/src/components/protected/topbar/components/ProfileModal.jsx
packages/main/src/components/protected/topbar/components/TopNavbar.jsx
packages/main/src/components/protected/topbar/styles/NotificationPreference.module.css
packages/main/src/components/protected/topbar/styles/PreferenceMenu.module.css
packages/main/src/components/protected/topbar/styles/ProfileModal.module.css
packages/main/src/components/protected/topbar/styles/StyledEditProfile.styled.js
packages/main/src/components/protected/topbar/styles/UserPreference.module.css

https://linear.app/team-grit/issue/FRO2-17/zuri-chat-profile-ui-story-point-3
1. Reduce the amount of white space
2. Remove the default background from input field
3. Disabled the jumping effect on user preference section
1. Reduced the amount of white space on the user preference section.
2. Remove the default background from input field on auto fill
3. Disabled the jumping effect on user preference section
Before
After

Fix/profile UI bugs

---

packages/main/src/components/protected/sidebar/components/Sidebar.jsx
packages/main/src/pages/protected/workspace/Workspace.style.js

fix error in plugins display

---

packages/root-config/src/applications.js
packages/root-config/src/assets/plugin.importmap.json

Imported the task manager plugin

feat: added task manager plugin

---

packages/main/src/components/footer/Footer.module.css
packages/main/src/components/top-navigation-bar/TopNavigationBar.jsx
packages/main/src/components/top-navigation-bar/TopNavigationBar.module.css

fix: fix styling issues in footer and navbar

---

packages/main/src/pages/static/contact-us/components/ContactMainBoard.jsx
packages/main/src/translations/translation-dictionary/pages/ContactUs.js

FE-112 translate Contact us page
https://linear.app/team-mallet/issue/FE-112/translate-contact-page
My PR fixes ID_linear_ticket_number -12
Translate Contact us page
i added translations to the contact us page

Feat/ FE-112/ Translate Contact Us Page 

---

packages/ui/src/message-board/MessageBoard.jsx
packages/ui/src/message-room-view-header/message-room-view-header.module.css

fix: Changed the Show Emoji Function to props

---

packages/main/src/components/top-navigation-bar/TopNavigationBar.jsx

Add zuri docs link to navbar
I added zuri docs link to navbar, and added a target of blank so it opens in a new tab

chore (FEC-115): added link to zuri docs on topnavbar

---

packages/main/src/components/protected/sidebar/components/DropRoom.jsx
packages/main/src/components/protected/sidebar/components/Sidebar.jsx
packages/root-config/src/assets/plugin.importmap.json

I fixed the bug regarding the input not focussing and also integrated the create channel endpoint

feat: create channel bug fix and endpoint integrated

---

packages/main/src/components/protected/sidebar/components/Drop.jsx
packages/main/src/components/protected/sidebar/components/DropRoom.jsx
packages/main/src/components/protected/sidebar/styles/Drop.module.css

Revert "Fix/create dms"

---

packages/main/src/components/protected/topbar/components/EditProfile.jsx
packages/main/src/components/protected/topbar/components/TopBarSearchModal.jsx
packages/ui/src/comment-board/CommentBoard.jsx
packages/ui/src/message-board/MessageBoard.jsx
packages/utilities/src/workspace.js

Refactor of #2824 PR

---

packages/main/src/components/general-loading/WorkspaceLoading.jsx
packages/main/src/components/general-loading/WorkspaceLoading.module.css
packages/main/src/pages/protected/workspace/Workspace.jsx
packages/main/src/pages/protected/workspace/Workspace.style.js
packages/root-config/src/assets/plugin.importmap.json
packages/root-config/src/zuri-root-config.js

- [x
https://user-images.githubusercontent.com/61692103/206876180-39b5c1dc-78ae-41b1-83de-88580a96848b.mov
] I am only making changes to files I was requested to.

workspace loader for better UX

---

packages/ui/src/comment-board/CommentBoard.jsx
packages/ui/src/comment-board/CommentBoard.styled.js

- Increase Thread section width
- Threads reply should start from the bottom of the parent message
Threads
Increase the width of the thread section
Position of comments in threads
Justified content space-between with comment wrapper and the input box 
https://user-images.githubusercontent.com/96787210/207002055-82660636-e4e8-46e5-b293-5387d507cf23.mp4

Threadsstyles fix

---

packages/ui/src/message-board/MessageBoard.jsx
packages/ui/src/message-pane-input/MessagePaneInput.jsx
packages/ui/src/message-pane-input/components/ToolbarBottom.jsx

**My PR Closes #issue_number
_here** or
Remove the file attachment in the input box once a user clicks send button
Added a pending state once a user sends a message
- [c] My commit messages styles matches our requested structure.
https://user-images.githubusercontent.com/96787210/207655310-a45b22e5-e9c4-4694-a184-4e2968d9d7eb.mp4

Fro pagination/comment/input

---

packages/main/src/components/protected/sidebar/components/Header.jsx
packages/main/src/components/protected/sidebar/components/ModalComponent.jsx
packages/main/src/components/protected/sidebar/components/Sidebar.jsx
packages/main/src/components/protected/sidebar/styles/ModalComponentStyles.module.css

**My PR improves display of sidebar menu** 
Add paddings in dropdown and change texts of  direct messages to remove underscore
**Improve sidebar**
Changed CSS styling for sidebar, changed English/default translation for direct messages

FRO: Made Style changes to sidebar dropdown to better match figma provided

---

packages/main/src/components/protected/topbar/components/Profile.jsx
packages/main/src/components/protected/topbar/components/ProfileMore.jsx

Fix Modals
Fixed View Profile Modal
https://user-images.githubusercontent.com/52335952/207524676-55f35851-3256-42fd-b9e6-1720966721df.mp4
https://user-images.githubusercontent.com/52335952/207524777-3fd47994-d36d-41f2-8bbd-03d433e3831b.mp4

Fix: Fix View Preference Modal not displaying in View Profile

---

packages/ui/src/message-room-details-dialog/MessageRoomDetailsDialog.jsx
packages/ui/src/message-room-details-dialog/MessageRoomDetailsDialog.styled.js

Fix channel Modal Leave, Archive and Delete Channel Modals not showing
I was asked to fix the modals that are not displaying
I fixed the channel modal leave, archive and delete channel modal not showing
https://user-images.githubusercontent.com/52335952/208321566-1d69424a-e930-4a62-97ad-15a4027697a5.mp4
https://user-images.githubusercontent.com/52335952/208321580-055b1aa8-1f54-4417-a968-30d9a38e07a0.mp4

Fix Channel Modal 

---

packages/root-config/src/zuri-root-config.js
packages/ui/src/message-board/MessageBoard.jsx

Fix: Undefined dom Element error fixed on page load

---

packages/main/src/pages/static/plugins/index.css

There was an issue with all font sizes on the page suddenly becoming small. so on investigation, the issue was coming from one App.css file setting all font sizes to 62.5%
I applied a fix of setting it back to 100% in the index.css file.
- [] I …

fix: style inheritance issue solved

---

packages/main/src/components/protected/sidebar/components/Sidebar.jsx
packages/ui/src/message-room-details-dialog/components/ArchiveChannel.jsx
packages/ui/src/message-room-details-dialog/components/DeleteChannel.jsx

Fixed the issues regarding the Delete channel and Archive channel functionalities.
- [] My code additions will …

feat: delete channel and archive channel functionality
